Repository codemindshub/centa-user-service, pull requests merged in 2024-12, with the labels that each got.

#5 CHORE(models): add custom user, organisation, roles, and permissions models
  .gitignore
  LICENSE
  README.md
  requirements.txt
  src/api/__init__.py
  src/api/admin.py
  src/api/apps.py
  src/api/migrations/__init__.py
  src/api/models.py
  src/api/paginators.py
  src/api/serializers.py
  src/api/tests.py
  src/api/urls.py
  src/api/utils.py
  src/api/views.py
  src/app.py
  src/cus/__init__.py
  src/cus/asgi.py
  src/cus/settings.py
  src/cus/urls.py
  src/cus/wsgi.py
  src/manage.py
  src/user_service/__init__.py
  src/user_service/admin.py
  src/user_service/apps.py
  src/user_service/migrations/__init__.py
  src/user_service/models.py
  src/user_service/permissions.py
  src/user_service/signals.py
  src/user_service/tests.py
  src/user_service/urls.py
  src/user_service/utils.py
  src/user_service/views.py
Labels: feat

#6 User Model Cleanup & Refactoring
  README.md
  requirements.txt
  src/cus/settings.py
  src/user_service/admin.py
  src/user_service/migrations/0001_initial.py
  src/user_service/models.py
Labels: enhancement, feat, bug fix

#7 CHORE: Added model and field valdators, customised admin dashboard
  src/user_service/admin.py
  src/user_service/migrations/0002_alter_organisation_table.py
  src/user_service/migrations/0003_alter_organisation_name_alter_organisation_owner_and_more.py
  src/user_service/models.py
  src/user_service/validators.py
Labels: feat, changes to PR
